substitutions:
  name: "multisensor"
  friendly_name: "Multisensor"
  area: "Room"
# illuminance_update_interval: "2s"
  hidden_ssid: "false"
  log_level: DEBUG
# pir_delay_off: "10s"
# pir_delay_on: "500ms"
  
dashboard_import:
  package_import_url: github://blaauboer/multisensors/multisensor-pir.yaml@main
  import_full_config: false # or true

packages:
  device_base: !include common/multisensor-base.yaml
  pir_base: !include common/pir-base.yaml
