substitutions:
  name: "multisensor"
  friendly_name: "Multisensor"
  area: "Room"
  illuminance_update_interval: "2s"
  hidden_ssid: "false"
  log_level: DEBUG

dashboard_import:
  package_import_url: github://blaauboer/multisensor.yaml@main
  import_full_config: false # or true

packages:
  device_base: !include common/multisensor-base.yaml
  ld2450_base: !include common/ld2450-base.yaml
  bh1750_base: !include common/bh1750-base.yaml
