substitutions:
  name: "multisensor"
  friendly_name: "Multisensor"
  area: "Room"
  illuminance_update_interval: "2s"
  hidden_ssid: "false"
  log_level: DEBUG
  pir_delay_off: "10s"
  pir_delay_on: "500ms"
  
dashboard_import:
  package_import_url: github://blaauboer/multisensors/multisensor-mmwave-pir-lux-ha.yaml@main
  import_full_config: false # or true

packages:
  device_base: !include common/multisensor-base.yaml
  ld2450_base: !include common/ld2450-base.yaml
  bh1750_base: !include common/bh1750-base.yaml
  pir_base: !include common/pir-base.yaml
  bme280_base: !include common/bme280-base.yaml
