number:
  - platform: template
    name: PIR delay off
    id: pir_delay_off
    entity_category: config
    device_class: duration
    unit_of_measurement: "s"
    icon: "mdi:timer-sand"
    optimistic: true
    restore_value: true
    initial_value: "10"
    min_value: 0
    max_value: 100
    step: 5
  - platform: template
    name: PIR delay on
    id: pir_delay_on
    entity_category: config
    device_class: duration
    unit_of_measurement: "ms"
    icon: "mdi:timer-sand"
    optimistic: true
    restore_value: true
    initial_value: "500"
    min_value: 0
    max_value: 1000
    step: 50
binary_sensor:
  - platform: gpio
    pin:
      number: 33
      mode:
        input: true
        pulldown: true
    name: "PIR bewegingssensor"
    id: pir_motion_sensor
    device_class: motion
    entity_category: diagnostic
    filters:
      - delayed_off: id(pir_delay_off)
      - delayed_on: id(pir_delay_on)
